/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.mpmgc.gameof15.app;


import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        System.out.println("Ciao");
    }
}
