/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import it.unicam.cs.mpmgc.communicationChannel.app.App;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
